stages: 
  - build
  - test
  - deploy

default:
  tags: [ unity ]

variables:
  BUILD_NAME: SafariCEO
  UNITY_ACTIVATION_FILE: Unity_v2022.3.24f1.alf
  UNITY_VERSION: "2022.3.24f1"
  IMAGE: unityci/editor
  IMAGE_VERSION: "3"
  UNITY_DIR: "SafariCEO"
  UNITY_USERNAME: "$UNITY_USERNAME"
  UNITY_PASSWORD: "$UNITY_PASSWORD"

image: $IMAGE:$UNITY_VERSION-base-$IMAGE_VERSION

.unity_before_script: &unity_before_script
  before_script:
    - chmod +x ./ci/before_script.sh && ./ci/before_script.sh
    
.cache: &cache
  cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$TEST_PLATFORM"
    paths:
      - $UNITY_DIR/Library/

.license: &license
  rules:
    - if: '$UNITY_LICENSE != null'
      when: always

get-activation-file-script:
    image: $IMAGE:2021.3.4f1-base-1.0.1
    rules:
        - if: '$UNITY_LICENSE == null'
          when: manual
    stage: build
    script:
        - chmod +x ./ci/get_activation_file.sh && ./ci/get_activation_file.sh
    artifacts:
        paths:
        - $UNITY_ACTIVATION_FILE
        expire_in: 10 min # Expiring this as artifacts may contain sensitive data and should not be kept public


.test: &test
  stage: test
  <<: *unity_before_script
  <<: *cache
  <<: *license
  script:
    - chmod +x ./ci/test.sh && ./ci/test.sh
  artifacts:
    when: always
    expire_in: 2 weeks
  coverage: /<Linecoverage>(.*?)</Linecoverage>/

test-playmode:
  <<: *test
  variables:
    TEST_PLATFORM: playmode

test-editmode:
  <<: *test
  variables:
    TEST_PLATFORM: editmode

.build: &build
  stage: build
  <<: *unity_before_script
  <<: *cache
  <<: *license
  script:
    - chmod +x ./ci/build.sh && ./ci/build.sh
  artifacts:
    paths:
      - $UNITY_DIR/Builds/


build-StandaloneWindows64:
  <<: *build
  tags: [unity]
  image: $IMAGE:$UNITY_VERSION-windows-mono-$IMAGE_VERSION
  variables:
    BUILD_TARGET: StandaloneWindows64

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - when: always