stages:
  - build_and_test
  - deploy

variables:
  BUILD_NAME: SafariCEO
  UNITY_VERSION: "2022.3.24f1"
  IMAGE: unityci/editor
  IMAGE_VERSION: "3"
  UNITY_DIR: "SafariCEO"
  UNITY_USERNAME: "$UNITY_USERNAME"
  UNITY_PASSWORD: "$UNITY_PASSWORD"

image: $IMAGE:$UNITY_VERSION-base-$IMAGE_VERSION

.unity_before_script: &unity_before_script
  before_script:
    - echo "Logging into Unity..."
    - unity-editor -logFile -batchmode -nographics -username "$UNITY_USERNAME" -password "$UNITY_PASSWORD" -quit

.cache: &cache
  cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$TEST_PLATFORM"
    paths:
      - $UNITY_DIR/Library/

.test: &test
  stage: build_and_test
  <<: *unity_before_script
  <<: *cache
  script:
    - chmod +x ./ci/test.sh && ./ci/test.sh
  artifacts:
    when: always
    expire_in: 2 weeks
  coverage: /<Linecoverage>(.*?)</Linecoverage>/

test-playmode:
  <<: *test
  variables:
    TEST_PLATFORM: playmode

test-editmode:
  <<: *test
  variables:
    TEST_PLATFORM: editmode

.build: &build
  stage: build_and_test
  <<: *unity_before_script
  <<: *cache
  script:
    - chmod +x ./ci/build.sh && ./ci/build.sh
  artifacts:
    paths:
      - $UNITY_DIR/Builds/

build-StandaloneLinux64:
  <<: *build
  variables:
    BUILD_TARGET: StandaloneLinux64

build-StandaloneOSX:
  <<: *build
  image: $IMAGE:$UNITY_VERSION-mac-mono-$IMAGE_VERSION
  variables:
    BUILD_TARGET: StandaloneOSX

build-StandaloneWindows64:
  <<: *build
  image: $IMAGE:$UNITY_VERSION-windows-mono-$IMAGE_VERSION
  variables:
    BUILD_TARGET: StandaloneWindows64

build-WebGL:
  <<: *build
  image: $IMAGE:$UNITY_VERSION-webgl-$IMAGE_VERSION
  variables:
    BUILD_TARGET: WebGL

pages:
  image: alpine:latest
  stage: deploy
  script:
    - mv "$UNITY_DIR/Builds/WebGL/${BUILD_NAME}" public
  artifacts:
    paths:
      - public
  only:
    - master

get-activation-file:
  stage: build_and_test
  image: $IMAGE:$UNITY_VERSION-base-$IMAGE_VERSION
  script:
    - echo "Generating manual activation file (.alf)..."
    - unity-editor -logFile -batchmode -nographics -createManualActivationFile -quit
    - mkdir -p artifacts
    - mv Unity_v*.alf artifacts/unity3d.alf
  artifacts:
    paths:
      - artifacts/unity3d.alf
    expire_in: 10 minutes
  when: manual

activate-license:
  stage: build_and_test
  image: $IMAGE:$UNITY_VERSION-base-$IMAGE_VERSION
  script:
    - echo "Activating Unity license..."
    - unity-editor -logFile -batchmode -nographics -manualLicenseFile artifacts/unity3d.ulf -quit
  when: manual
  dependencies:
    - get-activation-file

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "pipeline"
      when: never
    - when: always
